"""Builds and runs the Defender XDR MCP server.

The tool set itself is not hand-written: it's generated by FastMCP straight from
openapi/security.generated.yaml (Microsoft's own Graph OpenAPI spec, trimmed to the Incidents and
Advanced Hunting operations by scripts/fetch_spec.py). When Microsoft changes those endpoints,
re-running the generator picks it up - this file shouldn't need to change.

The spec ships as package data (src/defender_xdr_mcp/openapi/) rather than living outside the
package, and is loaded via importlib.resources rather than a path relative to this file's
location on disk. That's deliberate: `uv tool install` (and any other install path - a wheel, an
editable install, a zipped package) copies the *package* into an isolated environment but does not
carry along loose files that sit outside it, so a "few parents up from __file__" path breaks the
moment this stops being run straight out of a source checkout.
"""

from __future__ import annotations

from importlib import resources

import yaml
from dotenv import load_dotenv
from fastmcp import FastMCP
from fastmcp.server.providers.openapi.routing import MCPType, RouteMap

from .auth import build_http_client

SPEC_RESOURCE = resources.files("defender_xdr_mcp.openapi").joinpath("security.generated.yaml")

# GET -> read-only tool (list_incidents, get_incidents).
# PATCH -> mutating tool (update_incidents) - writes to the tenant's incident record.
# POST -> the runHuntingQuery action - read-only against tenant data (it runs a KQL query and
#   returns rows) but modeled as POST by Graph because it's an action, not a resource fetch.
# Every kept operation is mapped explicitly (rather than relying on FastMCP's default
# GET-is-a-tool heuristic) so it's unambiguous, from this file alone, which of the three tools
# can change something in the tenant: only update_incidents. Wire that distinction into your MCP
# client's permission rules (e.g. Claude Code's permissions.allow/ask) the same way.
ROUTE_MAPS = [
    RouteMap(methods=["GET"], mcp_type=MCPType.TOOL),
    RouteMap(methods=["POST"], mcp_type=MCPType.TOOL),
    RouteMap(methods=["PATCH"], mcp_type=MCPType.TOOL),
]


def build_server() -> FastMCP:
    load_dotenv()  # picks up .env in the current working directory, if present
    spec = yaml.safe_load(SPEC_RESOURCE.read_text())

    return FastMCP.from_openapi(
        openapi_spec=spec,
        client=build_http_client(),
        name="defender-xdr",
        route_maps=ROUTE_MAPS,
    )


def main() -> None:
    build_server().run()  # stdio transport by default - Claude Code spawns this as a subprocess


if __name__ == "__main__":
    main()
