"""Generate src/defender_xdr_mcp/openapi/security.generated.yaml from Microsoft's own Graph v1.0 OpenAPI spec.

Downloads the full (~40+ MB) spec published by Microsoft at
https://github.com/microsoftgraph/msgraph-metadata and slices out just the operations this
project exposes as MCP tools: Defender XDR Incidents (list / get / update) and Advanced Hunting
(runHuntingQuery). Only those operations plus the components (schemas/parameters/responses) they
actually reference are kept, so the generated spec stays small and self-contained.

Re-run this whenever Microsoft updates the upstream spec (e.g. new incident properties, new
hunting query options) to regenerate the MCP server's tool set without hand-editing anything.

Usage:
    uv run python scripts/fetch_spec.py
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path
from typing import Any

import yaml

SOURCE_URL = "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml"
OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "defender_xdr_mcp"
    / "openapi"
    / "security.generated.yaml"
)

# Paths -> the HTTP methods we keep on each. Everything else on these paths (create/delete/
# mergeIncidents/$count/etc.) is dropped: it's outside the two capabilities the Defender XDR docs
# name (https://learn.microsoft.com/en-us/defender-xdr/api-overview) — Incidents and Advanced
# Hunting — and outside the three documented Incidents methods (List/Get/Update).
KEPT_OPERATIONS: dict[str, set[str]] = {
    "/security/incidents": {"get"},
    "/security/incidents/{incident-id}": {"get", "patch"},
    "/security/microsoft.graph.security.runHuntingQuery": {"post"},
}

REF_RE = re.compile(r"^#/components/(schemas|parameters|responses|requestBodies|headers)/(.+)$")


def download(url: str) -> str:
    print(f"Downloading {url} ...", file=sys.stderr)
    with urllib.request.urlopen(url) as resp:  # noqa: S310 - trusted, hardcoded Microsoft URL
        return resp.read().decode("utf-8")


def find_refs(node: Any) -> set[tuple[str, str]]:
    """Recursively collect (category, name) for every $ref in node."""
    found: set[tuple[str, str]] = set()
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            m = REF_RE.match(ref)
            if m:
                found.add((m.group(1), m.group(2)))
        for v in node.values():
            found |= find_refs(v)
    elif isinstance(node, list):
        for item in node:
            found |= find_refs(item)
    return found


def close_over_components(
    initial_refs: set[tuple[str, str]], all_components: dict[str, dict[str, Any]]
) -> dict[str, dict[str, Any]]:
    """Starting from initial_refs, pull in every component transitively referenced."""
    kept: dict[str, dict[str, Any]] = {}
    pending = set(initial_refs)
    seen: set[tuple[str, str]] = set()

    while pending:
        category, name = pending.pop()
        if (category, name) in seen:
            continue
        seen.add((category, name))

        bucket = all_components.get(category, {})
        obj = bucket.get(name)
        if obj is None:
            print(f"WARNING: could not resolve #/components/{category}/{name}", file=sys.stderr)
            continue

        kept.setdefault(category, {})[name] = obj
        pending |= find_refs(obj)

    return kept


def main() -> None:
    raw = download(SOURCE_URL)
    print("Parsing YAML (this can take a little while for a 40+ MB file)...", file=sys.stderr)
    spec = yaml.safe_load(raw)

    filtered_paths: dict[str, Any] = {}
    for path, methods in KEPT_OPERATIONS.items():
        full_path_item = spec["paths"].get(path)
        if full_path_item is None:
            raise SystemExit(f"Path {path!r} not found in upstream spec - has Microsoft renamed it?")

        path_item: dict[str, Any] = {}
        for key, value in full_path_item.items():
            if key in ("get", "post", "patch", "put", "delete", "options", "head", "trace"):
                if key in methods:
                    path_item[key] = value
            else:
                # description, parameters (path-level, e.g. incident-id), etc.
                path_item[key] = value
        filtered_paths[path] = path_item

    # error response is referenced via 4XX/5XX on every kept operation but uses a non-standard
    # key ("error") that find_refs already picks up like any other $ref target.
    initial_refs = find_refs(filtered_paths)
    kept_components = close_over_components(initial_refs, spec["components"])

    output = {
        "openapi": spec["openapi"],
        "info": {
            "title": "Microsoft Defender XDR (via Graph Security API) - Incidents & Advanced Hunting",
            "description": (
                "Trimmed slice of Microsoft's Graph v1.0 OpenAPI spec, generated by "
                "scripts/fetch_spec.py. Covers only Defender XDR Incidents (list/get/update) and "
                "Advanced Hunting (runHuntingQuery), per "
                "https://learn.microsoft.com/en-us/defender-xdr/api-overview. "
                "Do not hand-edit - re-run the generator instead."
            ),
            "version": spec["info"]["version"],
        },
        "servers": [{"url": "https://graph.microsoft.com/v1.0"}],
        "paths": filtered_paths,
        "components": kept_components,
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w") as f:
        yaml.safe_dump(output, f, sort_keys=False, width=100)

    n_schemas = len(kept_components.get("schemas", {}))
    n_params = len(kept_components.get("parameters", {}))
    n_responses = len(kept_components.get("responses", {}))
    print(
        f"Wrote {OUTPUT_PATH} - {len(filtered_paths)} paths, "
        f"{n_schemas} schemas, {n_params} parameters, {n_responses} responses kept.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
